[package]
name = "block-header-unit"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = {workspace = true}
hex = { workspace = true }
alloy-sol-types = { workspace = true }
block-header-lib = { path = "../../lib" }