[package]
name = "block-header-recursive"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = {workspace = true, features = ["verify"]}
alloy-sol-types = { workspace = true }
sha2 = { workspace = true }
hex ={ workspace = true}
block-header-lib = { path = "../../lib" }

